package io.github.yeh35.channelopenapi.schma

data class Manager (
    val id: Long,
    val channelId: String,
    val accountId: String,
    val managerId: String,
    val username: String,
    val name: String,
    val email: String,
    val showEmailToFront: Boolean,
    val mobileNumber: String = "",
    val showMobileNumberToFront: Boolean,
    val showDescriptionToFront: Boolean,
    val role: String,
    val removed: Boolean,
    val displayAsChannel: Boolean,
    val defaultGroupWatch: String,
    val defaultDirectChatWatch: String,
    val defaultUserChatWatch: String,
    val chatAlertSound: String,
    val operatorScore: Double,
    val touchScore: Double,
    val operatorEmailReminder: Boolean,
    val operator: Boolean,
    val operatorScheduling: Boolean,
    val avatarUrl: String,
    val createdAt: Long,
)